### ISSUE TITLE
Bootstrapping to reduce noise?

### ISSUE THREAD

**Issue by most-vegetable-player** [RasoulAM/constant-weight-pir#1]
Can I use the bootstrapping operation to reduce noise when there is too much noise so that users can decrypt correctly ?

**Comment by RasoulAM** [comment]
The protocol is implemented to use levelled homomorphic encryption. So the parameters should be set such that the user can decrypt correctly. If you are getting incorrect results, increase the parameters.

Bootstrapping is theoretically possible for the underlying homomorphic cryptosystem, but 1) it is very slow and not recommended 2) is not implemented in SEAL
